
package WSer;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServices", targetNamespace = "http://Web/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServices {


    /**
     * 
     * @param cedula
     * @param contrase
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Login")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Login", targetNamespace = "http://Web/", className = "WSer.Login")
    @ResponseWrapper(localName = "LoginResponse", targetNamespace = "http://Web/", className = "WSer.LoginResponse")
    @Action(input = "http://Web/WebServices/LoginRequest", output = "http://Web/WebServices/LoginResponse")
    public String login(
        @WebParam(name = "cedula", targetNamespace = "")
        String cedula,
        @WebParam(name = "contrase", targetNamespace = "")
        String contrase);

}
